Se incluyó la gráfica de los puntos del usuario
Hay un error al espichar guardar y cerrar en esa ventana:

java.io.FileNotFoundException: C:\Users\juanj\Desktop\Proyecto DPOO\Proyecto-DPOO\data\clientes.csv (The process cannot access the file because it is being used by another process)